add 字幕正则补充
jxxghp/MoviePilot pull request #119
Opened 2023-08-14 11:48 UTC by yubanmeiqin9048

2023-08-14 22:44 UTC, jxxghp requested changes

2023-08-14 22:44 UTC, jxxghp commented on app/modules/filetransfer/__init__.py
> +                       r"|简体|简中|JPSC|CHS" \
CHS上面已经包含了吧？

2023-08-14 23:44 UTC, yubanmeiqin9048 commented
转移前
![2FD OS@_KS}4{G00{1{CG5G](https://github.com/jxxghp/MoviePilot/assets/64676973/cdb9f69c-1238-434d-b169-5dfcf8a38fa4)
转移后
![SG17~PMRN)FW2OH@~N{JXBX](https://github.com/jxxghp/MoviePilot/assets/64676973/1995b086-3a62-4c2b-aa20-a93320affab2)

2023-08-14 23:47 UTC, yubanmeiqin9048 commented on app/modules/filetransfer/__init__.py
> +                       r"|简体|简中|JPSC|CHS" \
但是转移不了

2023-08-15 10:00 UTC, jxxghp commented
> 转移前
> 
> ![2FD OS@_KS}4{G00{1{CG5G](https://github.com/jxxghp/MoviePilot/assets/64676973/cdb9f69c-1238-434d-b169-5dfcf8a38fa4)
> 
> 转移后
> 
> ![SG17~PMRN)FW2OH@~N{JXBX](https://github.com/jxxghp/MoviePilot/assets/64676973/1995b086-3a62-4c2b-aa20-a93320affab2)
> 
> 

第一排正则里面有chs，是不是大小写敏感的原因？

2023-08-15 10:28 UTC, yubanmeiqin9048 commented
> 

确实是大小写敏感，换成chs正常

2023-08-15 10:34 UTC, jxxghp commented
@yubanmeiqin9048 可以考虑加上大小写不敏感的参数

2023-08-15 10:44 UTC, yubanmeiqin9048 commented
@jxxghp 现在已经是大小写不敏感了吧
```Python
if re.search(_zhcn_sub_re, file_item.stem, re.I):
                        new_file_type = ".chi.zh-cn"
```

2023-08-15 10:52 UTC, yubanmeiqin9048 commented
> > 
> 
> 确实是大小写敏感，换成chs正常

不对，换成小写也不行（忘切容器了

2023-08-16 01:30 UTC, closed without merging