fix 首页继续观看、最近添加排除黑名单媒体库 && fix #907
jxxghp/MoviePilot pull request #1328
Opened 2024-01-08 05:11 UTC by thsrite

MediaServerItem应用了MEDIASERVER_SYNC_BLACKLIST同步到MoviePilot。

首页媒体统计、继续观看、最近添加改为从MediaServerItem判断是否可查询展示

已达到应用MEDIASERVER_SYNC_BLACKLIST配置的目的

2024-01-09 09:52 UTC, jxxghp commented
不是很优雅，如果能返回媒体库的信息就好了。

2024-01-10 02:55 UTC, thsrite commented
> 不是很优雅，如果能返回媒体库的信息就好了。

这下优雅了点，返回了正在播放、近期添加的item的path，根据排除黑名单的path做比对，也能达到效果。
不过只支持emby/jellyfin，plex不知道咋改

2024-01-10 03:00 UTC, jxxghp requested changes

2024-01-10 03:00 UTC, jxxghp commented on app/modules/emby/emby.py
> +                   f"Limit=100&MediaTypes=Video&api_key={self._apikey}&Fields=ProductionYear,Path")
显示条数要控制吧？

2024-01-10 03:19 UTC, thsrite commented on app/chain/dashboard.py
> +            series = self.dboper.list_by_type(mtype="电视剧") or []
> 就是个统计数字，还要查数据库，太重了，这个不改了。

嗯 revert了

2024-01-10 03:20 UTC, thsrite commented on app/modules/emby/emby.py
> +                   f"Limit=100&MediaTypes=Video&api_key={self._apikey}&Fields=ProductionYear,Path")
> 显示条数要控制吧？

![image](https://github.com/jxxghp/MoviePilot/assets/54088512/4b5ff1f2-b610-4ee6-8eb3-5595445c2e89)
下面控制了。
防止过滤的太多，没剩几条显示了

2024-01-10 04:25 UTC, merged