faet: 可供自定义cookie同步
jxxghp/MoviePilot pull request #1812
Opened 2024-04-01 14:12 UTC by jeblove

feat: sync_cookies方法可自提供数据
feat: 新增移除指定id定时任务

2024-04-01 22:29 UTC, jxxghp requested changes

2024-04-01 22:29 UTC, jxxghp commented on app/scheduler.py
> +    def remove_id_job(self, id: str) -> bool:
已存在相同功能函数

2024-04-02 01:16 UTC, jeblove commented on app/scheduler.py
> +    def remove_id_job(self, id: str) -> bool:
已存在的`remove_plugin_job(self, pid: str)`无法用于移除非插件定时任务

2024-04-02 01:27 UTC, jxxghp commented on app/scheduler.py
> +    def remove_id_job(self, id: str) -> bool:
> 已存在的`remove_plugin_job(self, pid: str)`无法用于移除非插件定时任务

非插件的为何要移除？

2024-04-02 01:31 UTC, jeblove commented on app/scheduler.py
> +    def remove_id_job(self, id: str) -> bool:
> > 已存在的`remove_plugin_job(self, pid: str)`无法用于移除非插件定时任务
> 
> 非插件的为何要移除？

例如，可以停止CookieCloud，实现只由插件同步站点cookies

2024-04-02 02:28 UTC, closed without merging