feat(common): 增加 `version_comparison` 方法
jxxghp/MoviePilot pull request #3325
Opened 2024-12-04 13:10 UTC by Aqr-K

- 可用于给插件或主程序进行版本比对使用，判断是否使用新特性；适用场景：插件只支持某个版本以上；插件更新版本号比对更规范，贴近 `app` 版本号要求等。

2024-12-04 22:57 UTC, jxxghp requested changes

2024-12-04 22:57 UTC, jxxghp commented on app/utils/common.py
> +def version_comparison(standard_version) -> Optional[bool]:
1. 入参请声明类型
2. 这个是业务方法，还有对VERSION的引用，放utils.common不合适

2024-12-05 05:42 UTC, Aqr-K commented on app/utils/common.py
> +def version_comparison(standard_version) -> Optional[bool]:
重构成装饰器了，现在 `VERSION` 的引入只是作为默认值，可以手动指定要比对的版本。不局限于只做系统版本的比对，通用性更强点。看看还需不需要换个地方放？换的话放哪里比较合适？

2024-12-05 09:09 UTC, jxxghp commented on app/utils/common.py
> +def version_comparison(standard_version) -> Optional[bool]:
是不是放systemchain就行了，这个是带业务逻辑的。

2024-12-05 09:40 UTC, Aqr-K commented on app/utils/common.py
> +def version_comparison(standard_version) -> Optional[bool]:
好，业务逻辑我移到app/chain/system中。还需要引用方法，保留装饰器功能吗？

2024-12-05 10:17 UTC, closed without merging