fix 自定义订阅插件增加识别按钮
jxxghp/MoviePilot pull request #564
Opened 2023-09-12 04:44 UTC by thsrite

2023-09-12 22:43 UTC, jxxghp requested changes

2023-09-12 22:43 UTC, jxxghp commented on app/db/systemconfig_oper.py
> +        self.plugindata = PluginDataOper(self._db)
不应该在systemcinfig中访问plugindata

2023-09-12 22:43 UTC, jxxghp commented on app/chain/__init__.py
> +    def scrape_metadata(self, path: Path, mediainfo: MediaInfo, scrap_metadata: bool = settings.SCRAP_METADATA) -> None:
参数名避免与函数名查同

2023-09-12 22:43 UTC, jxxghp commented on app/plugins/rsssubscribe/__init__.py
> +            self._recognization = config.get("recognization")
暂时不加这个功能，后面再看吧。

2023-09-13 03:52 UTC, jxxghp requested changes

2023-09-13 03:52 UTC, jxxghp commented on app/db/systemconfig_oper.py
> +        self._plugindata = PluginData()
systemconfig不应访问plugindata

2023-09-13 03:52 UTC, jxxghp commented on app/db/systemconfig_oper.py
> +        self._plugindata.del_plugin_data_by_plugin_id(db=self._db, plugin_id=key)
同上

2023-09-13 04:00 UTC, thsrite commented on app/db/systemconfig_oper.py
> +        self._plugindata.del_plugin_data_by_plugin_id(db=self._db, plugin_id=key)
> 同上

我回滚掉了。
我看SystemConfig.list(self._db)也是访问的数据层

2023-09-13 04:04 UTC, merged