fix #553 修复unraid删除资源慢的问题
jxxghp/MoviePilot pull request #612
Opened 2023-09-18 03:42 UTC by thsrite

2023-09-18 03:46 UTC, jxxghp requested changes

2023-09-18 03:46 UTC, jxxghp commented on app/chain/transfer.py
> +            files = glob.glob(f"{os.path.join(path.parent, os.path.splitext(path.name)[0])}*")
统一使用pathlib

2023-09-18 03:46 UTC, jxxghp commented on app/chain/transfer.py
> +                if str(parent_path.name) in library_root_names:
这样确定安全吗？
目录同步的不一定是这个结构吧？

2023-09-18 03:47 UTC, jxxghp requested changes

2023-09-18 03:47 UTC, jxxghp commented on app/api/endpoints/history.py
> +            TransferChain(db).delete_files(Path(history.dest), False if len(other_history) - 1 > 0 else True)
以历史记录为准不准确

2023-09-18 05:53 UTC, thsrite commented on app/api/endpoints/history.py
> +            TransferChain(db).delete_files(Path(history.dest), False if len(other_history) - 1 > 0 else True)
> 以历史记录为准不准确

如果全用mp处理的话，历史记录应该也准

2023-09-19 08:07 UTC, jxxghp requested changes

2023-09-19 08:07 UTC, jxxghp commented on app/chain/transfer.py
> +            files = glob.glob(f"{Path(path.parent).joinpath(str(path.name).split('.')[0])}*")
取无后缀名称用.stem就行

2023-09-19 08:07 UTC, jxxghp commented on app/chain/transfer.py
> +        files = SystemUtils.list_files(path.parent, settings.RMT_MEDIAEXT)
可以写个新方法，不用算总数，而是遍历到一个文件就返回True，这样就快了，也不用判断目录名了。

2023-09-19 08:35 UTC, jxxghp requested changes

2023-09-19 08:35 UTC, jxxghp commented on app/chain/transfer.py
> +                    files = SystemUtils.list_files(parent_path, settings.RMT_MEDIAEXT)
这里也改一下

2023-09-19 08:44 UTC, thsrite commented on app/chain/transfer.py
> +                    files = SystemUtils.list_files(parent_path, settings.RMT_MEDIAEXT)
> 这里也改一下

已改

2023-09-19 09:08 UTC, merged